data_ingestion_cleaning_transformation_task:
  description: >
    Process the CSV File. Inspect the data and provide a summary including:
    - The column names	
    - Any missing values
    - Basic insights such as potential predictors of churn
    - Any anomalies, duplicates, or notable distributions
    
    Answer the following questions as well
    
    1. Were you able to locate the file?
    2. What are the main patterns in the data?
    2. What insights can you provide about customer behavior?
    3. Are there any anomalies or interesting trends?

    Use the 'CSVSearchTool' to process the file and search for relevant information.

    You may choose to sample upto 10000 rows of data if the file is too long but ensure 
    it is a stratified sample to ensure each subgroup (strata) of a population is 
    adequately represented in the sample, improving the precision of estimates and 
    reducing sampling variability.
  expected_output: >
    Comprehensive analysis of the CSV data with key insights and patterns
    A clear, concise report that describes the dataset, its structure, any quality issues, and 2–3 initial hypotheses or areas 
    to explore further. 
  agent: data_ingestor

eda_task:
  description: >
    Identify trends, anomalies, feature relationships, and basic correlations about {topic}
  expected_output: >
    Visual summaries, EDA report, feature candidates for causal/statistical analysis
  agent: exploratory_analyst

statistical_analysis_task:
  description: >
    Perform appropriate hypothesis tests, assess distributions and interdependencies to understand {topic}
  expected_output: >
    Statistical test results with interpretation and p-values
  agent: statistical_analyst
  
causal_inference_modeling_task:
  description: >
    Apply causal inference techniques (e.g., matching, DiD, IV, regression, Bayesian networks) 
    to assess cause-effect relationships to understand the causes of {topic}
  expected_output: >
    Causal estimates with assumptions, methodology, and confidence intervals
  agent: statistical_analyst
  
visualization_generation_task:
  description: >
    Create plots that support findings (trends, relationships, causal diagrams, confidence intervals) to explain {topic}
  expected_output: >
    Exportable visual assets, interactive dashboard or static plots
  agent: visualization_analyst
  
insights_reports_generation_task:
  description: >
    Consolidate findings into a clear, human-readable report that summarizes the end-to-end analysis for {topic}
  expected_output: >
    Final structured report in Markdown (md) format, with embedded visuals and recommendations
  agent: visualization_analyst
